### PR TITLE
jruby in CI

### PR DESCRIPTION
**Pull request by HoneyryderChuck**
enabling jruby in CI, allowing it to fail

### CODE REVIEW

**Comment by HoneyryderChuck** [comment]
@janko Jruby passing with rails 6.0 and 5.2!

**Comment by janko** [comment]
@HoneyryderChuck Wow, that is awesome to hear!

I really appreciate all the effort you've put into this. I always try to make libraries work with JRuby, but here I just didn't have energy left to figure it out, and you've just gone ahead and done it ❤️ 

I've noticed that activerecord-jdbc-adapter started with the `<MAJOR><MINOR>` versions from Rails 5.0 (where `<MAJOR><MINOR>` matches the Rails version). So perhaps we could exclude Rails 4.2 from JRuby support and save ourselves some trouble.

**Comment by HoneyryderChuck** [comment]
+1 for removing 4.2 @janko .

How about 5.0? Should one do the extra effort there? I'm starting to feel that jruby support should be more restrictive regarding the number of supported rails versions, specially considering the historical activerecord-jdbc-adapter incompatibilities.

**Comment by janko** [comment]
Yeah, I’m happy with whatever support you have time and energy for. Latest minor versions of two Rails 5 and 6 is pretty good IMO.

I’ve seen gems that maintain support for multiple versions of JRuby, which is unthinkable for me 😛

**Comment by HoneyryderChuck** [comment]
perfect! will remove those versions then.

Regarding multiple versions of jruby, that's unfeasible nowadays. I usually do "latest version" support. But rails is smth else, I guess.

**Comment by HoneyryderChuck** [comment]
@janko ready to merge, if you agree.

**Comment by janko** [comment]
Perfect, looks good to me, merge away 👍

**Pull request merged**
