### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by benkoshy**
Specifying the exact location reduces the cognitive workload for those not new to the library, gets them flying almost immediately a "hello-world" example, almost without thinking. 

I hope this is helpful.

### CODE REVIEW

**Comment by janko** [comment]
I think `config/initializers/sequel.rb` makes more sense, because you are initializing Sequel, you're just using an extension from another gem. In my application, I'm using sequel-activerecord_connection for my main database, but then I'm also initializing an actual Sequel connection to another database (which doesn't use Active Record), so it's convenient to be able to put both in the same file. Also, I think the `./` isn't necessary.

However, what about Hanami or Roda users, do they also need to put this code into `config/initializers/`? That's why I'm careful about making the documentation Rails-specific, as I also want it to make sense for people not using Rails.

**Comment by benkoshy** [comment]
Hi Janko

I have force pushed with the following changes:

- a note on framework agnosticism
- a change to the file name and path

(Not every suggestion i make is a  good one, feel free to close if it is not suitable etc.)

**Comment by janko** [comment]
I like the changes, I agree they improve clarity. Thanks for following-up 👍🏻

**Comment by janko** [comment]
I like the changes, I agree they improve clarity. Thanks for following-up 👍🏻

**Pull request merged**
